# Noise2Void training run parameters

# These are used in various places
run_directory: "runs/IrGLC/run_{index}"  # {index} is replaced with the next integer if necessary
image_size: 512
channels: ["HAADF",]

model:  # Used to define the model
  name: "UNet"
  depth: 4
  first_layer_channels: 64
  initial_kernel_size: 5
  state_savename: "model_state.pt"    # Where to save the raw weights
  traced_savename: "traced_model.pt"  # Where to save the JIT/traced ScriptModule

trainer:
  learning_rate: 2e-5  # Adam optimiser learning rate
  batch_size: 7
  epochs: 32
  spacing: 24
  test_fraction: 0.2

dataset:
  type: "IridiumGLCVideo"
  px_scale: 0.007   # Size of pixels in nanometres
  example_index: 5  # The index to reserve for validation

  predicter:
    video_fps: 10
    device: "cuda"  # A valid PyTorch device string
    batch_size: 4

# Logging config
defaults:
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none