# Noise2Void training run parameters

# These are used in various places
run_directory: "runs/WS2/run_{index}"  # {index} is replaced with the next integer if necessary
image_size: 512
channels: ["HAADF", "BF"]

model:  # Used to define the model
  name: "UNet"
  depth: 4
  first_layer_channels: 32
  initial_kernel_size: 5
  state_savename: "model_state.pt"    # Where to save the raw weights
  traced_savename: "traced_model.pt"  # Where to save the JIT/traced ScriptModule

trainer:
  learning_rate: 1e-5  # Adam optimiser learning rate
  batch_size: 16
  epochs: 32
  spacing: 36
  test_fraction: 0.2

dataset:
  type: "WS2"
  px_scale: 0.007   # Size of pixels in nanometres
  example_index: 5  # The index to reserve for validation